# This refers to the plugin version. Do not change this or else you might encounter issues
version: ${modified.version}

# This is the base cost of using a waypoint
rate: 1

# This refers to how many blocks the rate represents
distance: 500

# This refers to if activated waypoints are available to all players or to whoever activated it only
global-waypoints: false

host: localhost
port: 3306
database: minecraft
username: root
password: password
