database:
  url: jdbc:mysql://phpmyadmin.grylhosting.com:3306/1852?serverTimezone=UTC
  username: 1852
  password: c8035658ec

exp-per-block: 0.01
waypoint-prefix: Waypoint
selector-title: Select Location
