version: ${modified.version}

# MAIN PLUGIN CONFIG FILE
# =========================
# filename: waypoints.db - File to load for SQLite
# rate: 1 - Base cost of fast travelling
# distance - 500 - How many blocks the rate represents

filename: waypoints.db
rate: 1
distance: 500
