main: ${project.groupId}.${project.artifactId}.MainApp
name: ${project.name}
version: ${modified.version}
author: lunarpatriots
api-version: 1.16

commands:
  validate:
    description: Checks validity of all waypoints in the currently loaded world
    usage: /validate
  clean:
    description: Removes all invalid waypoints
    usage: /clean
  waypoints:
    description: Lists waypoints in the given region
    usage: /waypoints
  import:
    description: Import info from json file
    usage: /import <json file>
