main: ${project.groupId}.${project.artifactId}.MainApp
name: ${project.name}
version: ${project.version}
author: lunarpatriots
api-version: 1.16

commands:
  validate:
    description: Checks validity of all waypoints in the currently loaded world
    usage: /validate
